spring:
  datasource:
    username: postgres
    password: "0000"
    url: jdbc:postgresql://localhost:5432/movies
  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

project:
  posters:
    path: posters

base:
  url: http://localhost:8080/file/