spring:
  datasource:
    username: postgres
    password: "0000"
    url: jdbc:postgresql://localhost:5432/movies
  jpa:
    hibernate:
      ddl-auto: update   # create-drop -> przy starcie usuwa poprzednie i tworzy nowe tabele i kolumny na podstawie encji
#      show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: wojciechwazny444@gmail.com
    password: toix rdia cmnn jamh

logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.hibernate.SQL: #DEBUG
    org.hibernate.orm.jdbc.bind: #TRACE

project:
  posters:
    path: posters
  mail:
    name: wojciechwazny444@gmail.com
    subject: Verification code.

base:
  url: http://localhost:8080/file/

jwt:
  secret: BF7FD11ACE545745B7BA1AF98B6F156D127BC7BB544BAB6A4FD74E4FC7